package util;

public enum ModelType {
    AMENITIES,
    AMENITIESINRESIDENCE,
    APPLICATION,
    APPLICATIONSFORRESIDENCE,
    CAMPUS,
    CFA,
    CFARESIDENTS,
    LIVESWITH,
    RESIDENCE,
    RESIDENCEONCAMPUS,
    RESIDENCESTAFF,
    RESIDENT,
    ROOMALLOCATIONINFO,
    ROOMINFO,
    WORKS
}
